version: '3'

services:
  postgres:
    image: postgres:14
    networks:
      - security-profitability
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "securityprofitability"
      POSTGRES_PASSWORD: "securityprofitability"
      POSTGRES_DB: "securityprofitability"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "postgres-data:/var/lib/postgresql/data/pgdata"

  jaeger:
    image: jaegertracing/all-in-one:1.37
    environment:
      - "COLLECTOR_OTLP_ENABLED=true"
    ports:
      - 16686:16686 # dashboard
      - 16685:16685
      - 14250:14250
      - 4317:4317 # otlp grpc
      - 4318:4318 # otlp http
    networks:
      - fibonacci-api

networks:
  fibonacci-api: {}
